# Generated by Django 3.2.3 on 2021-05-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('document', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
